### --- Base image versions --- ###
FROM node:20-alpine AS base

# Install dependencies only when needed
FROM base AS deps

# System deps for Next.js/Prisma on Alpine
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install Node dependencies with pnpm
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN corepack enable pnpm && pnpm i --frozen-lockfile

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build arguments for environment variables (QSIGN MAIN ENVS)
ARG AUTH_GOOGLE_ID
ARG AUTH_GOOGLE_SECRET
ARG GOOGLE_MAPS_API_KEY
ARG AUTH_SECRET
ARG AUTH_URL

ARG NEXT_PUBLIC_SITE_URL

ARG DATABASE_URL

ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG SUPABASE_SERVICE_ROLE_KEY

ARG EMAIL_HOST
ARG EMAIL_PORT
ARG EMAIL_USER
ARG EMAIL_PASS
ARG EMAIL_FROM
ARG EMAIL_FROM_NAME

ARG VIDEO_SDK_API_KEY
ARG VIDEO_SDK_SECRET
ARG NEXT_PUBLIC_VIDEO_SDK_API_KEY

ARG DOCONCHAIN_CLIENT_KEY
ARG DOCONCHAIN_CLIENT_SECRET
ARG DOCONCHAIN_EMAIL
ARG DOCONCHAIN_ORGANIZATION_ID
ARG DOCONCHAIN_API_URL
ARG DOCONCHAIN_API_TOKEN
ARG DOCOCHAIN_API_TOKEN

ARG HYPERVERGE_APP_ID
ARG HYPERVERGE_APP_KEY
ARG HYPERVERGE_WORKFLOW_ID
ARG HYPERVERGE_API_URL
ARG HYPERVERGE_DIRECT_LIVENESS_ENABLED

# Environment variables
ENV NODE_ENV=production
ENV AUTH_TRUST_HOST=true

ENV AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
ENV AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
ENV GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
ENV AUTH_SECRET=${AUTH_SECRET}
ENV AUTH_URL=${AUTH_URL}

ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}

ENV DATABASE_URL=${DATABASE_URL}

ENV NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
ENV SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}

ENV EMAIL_HOST=${EMAIL_HOST}
ENV EMAIL_PORT=${EMAIL_PORT}
ENV EMAIL_USER=${EMAIL_USER}
ENV EMAIL_PASS=${EMAIL_PASS}
ENV EMAIL_FROM=${EMAIL_FROM}
ENV EMAIL_FROM_NAME=${EMAIL_FROM_NAME}

ENV VIDEO_SDK_API_KEY=${VIDEO_SDK_API_KEY}
ENV VIDEO_SDK_SECRET=${VIDEO_SDK_SECRET}
ENV NEXT_PUBLIC_VIDEO_SDK_API_KEY=${NEXT_PUBLIC_VIDEO_SDK_API_KEY}

ENV DOCONCHAIN_CLIENT_KEY=${DOCONCHAIN_CLIENT_KEY}
ENV DOCONCHAIN_CLIENT_SECRET=${DOCONCHAIN_CLIENT_SECRET}
ENV DOCONCHAIN_EMAIL=${DOCONCHAIN_EMAIL}
ENV DOCONCHAIN_ORGANIZATION_ID=${DOCONCHAIN_ORGANIZATION_ID}
ENV DOCONCHAIN_API_URL=${DOCONCHAIN_API_URL}
ENV DOCONCHAIN_API_TOKEN=${DOCONCHAIN_API_TOKEN}
ENV DOCOCHAIN_API_TOKEN=${DOCOCHAIN_API_TOKEN}
  
ENV HYPERVERGE_APP_ID=${HYPERVERGE_APP_ID}
ENV HYPERVERGE_APP_KEY=${HYPERVERGE_APP_KEY}
ENV HYPERVERGE_WORKFLOW_ID=${HYPERVERGE_WORKFLOW_ID}
ENV HYPERVERGE_API_URL=${HYPERVERGE_API_URL}
ENV HYPERVERGE_DIRECT_LIVENESS_ENABLED=${HYPERVERGE_DIRECT_LIVENESS_ENABLED}

ENV SKIP_ENV_VALIDATION=1
ENV ENABLE_STANDALONE=true

# Build the project and its dependencies
RUN corepack enable pnpm && pnpm db:generate && pnpm build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# Set the correct permission for prerender cache
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# server.js is created by next build from the standalone output
# https://nextjs.org/docs/pages/api-reference/next-config-js/output
CMD ["node", "server.js"]
