import { createEnv } from "@t3-oss/env-nextjs"
import { z } from "zod/v4"

export const env = createEnv({
	server: {
		AUTH_SECRET: process.env.NODE_ENV === "production" ? z.string() : z.string().optional(),
		AUTH_URL: z.string().optional(),
		AUTH_GOOGLE_ID: z.string(),
		AUTH_GOOGLE_SECRET: z.string(),
		DATABASE_URL: z.string().min(1),
		EMAIL_FROM_NAME: z.string(),
		EMAIL_FROM: z.string(),
		EMAIL_HOST: z.string(),
		EMAIL_PASS: z.string(),
		EMAIL_PORT: z.coerce.number(),
		EMAIL_USER: z.string(),
		NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
		PORT: process.env.PORT ? z.coerce.number() : z.coerce.number().default(3000),
		SEED_VALUE: z.coerce.number().optional(),
	},
	client: {},
	runtimeEnv: {
		AUTH_SECRET: process.env.AUTH_SECRET,
		AUTH_URL: process.env.AUTH_URL,
		AUTH_GOOGLE_ID: process.env.AUTH_GOOGLE_ID,
		AUTH_GOOGLE_SECRET: process.env.AUTH_GOOGLE_SECRET,
		DATABASE_URL: process.env.DATABASE_URL,
		EMAIL_FROM_NAME: process.env.EMAIL_FROM_NAME,
		EMAIL_FROM: process.env.EMAIL_FROM,
		EMAIL_HOST: process.env.EMAIL_HOST,
		EMAIL_PASS: process.env.EMAIL_PASS,
		EMAIL_PORT: process.env.EMAIL_PORT,
		EMAIL_USER: process.env.EMAIL_USER,
		NODE_ENV: process.env.NODE_ENV,
		PORT: process.env.PORT,
		SEED_VALUE: process.env.SEED_VALUE,
	},
	skipValidation: !!process.env.SKIP_ENV_VALIDATION,
	emptyStringAsUndefined: true,
})
