import { createEnv } from "@t3-oss/env-nextjs"
import { z } from "zod/v4"

export const env = createEnv({
	server: {
		AUTH_GOOGLE_ID: z.string(),
		AUTH_GOOGLE_SECRET: z.string(),
		AUTH_SECRET: process.env.NODE_ENV === "production" ? z.string() : z.string().optional(),
		AUTH_TRUST_HOST: z.string().optional(),
		AUTH_URL: z.string().optional(),
		DATABASE_URL: z.string().min(1),
		DOCOCHAIN_API_TOKEN: z.string().optional(),
		DOCOCHAIN_API_URL: z.string().optional(),
		DOCOCHAIN_ORGANIZATION_ID: z.string().optional(),
		DOCOCHAIN_CLIENT_KEY: z.string().optional(),
		DOCOCHAIN_CLIENT_SECRET: z.string().optional(),
		EMAIL_FROM_NAME: z.string(),
		EMAIL_FROM: z.string(),
		EMAIL_HOST: z.string(),
		EMAIL_PASS: z.string(),
		EMAIL_PORT: z.coerce.number(),
		EMAIL_USER: z.string(),
		HYPERVERGE_API_URL: z.string().optional(),
		HYPERVERGE_APP_ID: z.string(),
		HYPERVERGE_APP_KEY: z.string(),
		HYPERVERGE_WORKFLOW_ID: z.string(),
		HYPERVERGE_DIRECT_LIVENESS_ENABLED: z.string().optional().default("false"),
		NODE_ENV: z.enum(["development", "test", "production"]).default("development"),

		PORT: process.env.PORT ? z.coerce.number() : z.coerce.number().default(3000),
		SEED_VALUE: z.coerce.number().optional(),
		SUPABASE_SERVICE_ROLE_KEY: z.string(),
		VIDEO_SDK_API_KEY: z.string(),
		VIDEO_SDK_SECRET: z.string(),
	},
	client: {
		NEXT_PUBLIC_SUPABASE_URL: z.url(),
		NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string(),
		NEXT_PUBLIC_VIDEO_SDK_API_KEY: z.string(),
	},
	runtimeEnv: {
		AUTH_GOOGLE_ID: process.env.AUTH_GOOGLE_ID,
		AUTH_GOOGLE_SECRET: process.env.AUTH_GOOGLE_SECRET,
		AUTH_SECRET: process.env.AUTH_SECRET,
		AUTH_TRUST_HOST: process.env.AUTH_TRUST_HOST,
		AUTH_URL: process.env.AUTH_URL,
		DATABASE_URL: process.env.DATABASE_URL,
		DOCOCHAIN_API_TOKEN: process.env.DOCOCHAIN_API_TOKEN || process.env.DOCONCHAIN_API_TOKEN,
		DOCOCHAIN_API_URL: process.env.DOCOCHAIN_API_URL || process.env.DOCONCHAIN_API_URL,
		DOCOCHAIN_ORGANIZATION_ID: process.env.DOCOCHAIN_ORGANIZATION_ID || process.env.DOCONCHAIN_ORGANIZATION_ID,
		DOCOCHAIN_CLIENT_KEY: process.env.DOCOCHAIN_CLIENT_KEY || process.env.DOCONCHAIN_CLIENT_KEY,
		DOCOCHAIN_CLIENT_SECRET: process.env.DOCOCHAIN_CLIENT_SECRET || process.env.DOCONCHAIN_CLIENT_SECRET,
		EMAIL_FROM_NAME: process.env.EMAIL_FROM_NAME,
		EMAIL_FROM: process.env.EMAIL_FROM,
		EMAIL_HOST: process.env.EMAIL_HOST,
		EMAIL_PASS: process.env.EMAIL_PASS,
		EMAIL_PORT: process.env.EMAIL_PORT,
		EMAIL_USER: process.env.EMAIL_USER,
		HYPERVERGE_API_URL: process.env.HYPERVERGE_API_URL,
		HYPERVERGE_APP_ID: process.env.HYPERVERGE_APP_ID,
		HYPERVERGE_APP_KEY: process.env.HYPERVERGE_APP_KEY,
		HYPERVERGE_WORKFLOW_ID: process.env.HYPERVERGE_WORKFLOW_ID,
		HYPERVERGE_DIRECT_LIVENESS_ENABLED: process.env.HYPERVERGE_DIRECT_LIVENESS_ENABLED,
		NODE_ENV: process.env.NODE_ENV,
		NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
		NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
		NEXT_PUBLIC_VIDEO_SDK_API_KEY: process.env.NEXT_PUBLIC_VIDEO_SDK_API_KEY,
		PORT: process.env.PORT,
		SEED_VALUE: process.env.SEED_VALUE,
		SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
		VIDEO_SDK_API_KEY: process.env.VIDEO_SDK_API_KEY,
		VIDEO_SDK_SECRET: process.env.VIDEO_SDK_SECRET,
	},
	skipValidation: !!process.env.SKIP_ENV_VALIDATION,
	emptyStringAsUndefined: true,
})
